### ISSUE TITLE
feeds folder not created / empty

### ISSUE THREAD

**Issue by unspacyar** [JadedCtrl/Pogger#10]
I tried downloading and compiling your source (today, march 23).  The compilation went  without issues (in Haiku 32 bit, but using the secondary architecture).  However, I found this problem:

- The application don't create the /boot/home/feeds folder.  I understand that there is a recent commit that fixed this problem, but for some reason, apparently don't work.

- I also tried creating the folder manually, but after that, still don't see any new feed downloaded.

I opened the Subscriptions configuration folder (/boot/home/config/settings/Pogger/Subscriptions), and opened the files using DiskProbe, and I see information about recent updates for the feed.  But for some reason, the file in the home/feeds folder is not created.

**Comment by JadedCtrl** [comment]
Thanks for giving it a go! For the feeds folder, it isn't created until it's needed― when  a new entry's going to be put into it. This is a bit confusing, I should move that to when the program's started.

When you subscribe to a new feed, it sets the "last updated" date to the day you subscribe, so it won't spam you with a bunch of old posts― so not getting any posts at first (or only getting a couple) is completely normal. If you want to get the old posts, you could change the "Feed:when" (last updated) attribute for the subscription.

You can [try this Haiku Blog](https://0x0.st/-qja.zip) subscription (already spoofed with "last updated" as December 2020), or copy its Feed:when attribute to your other feed.

**Comment by unspacyar** [comment]
Thank you for the feedback!  It worked with your subscription!  This is just a suggestion, based in my previous experience with others RSS readers:  maybe in that cases the program could just retrieve the last feed available?  In this way the user could get some feedback that their subscription was added  correctly.  

IIRC, others RSS readers manage some "max amount" of feeds that could be retrieved.

Anyways, thank you really much for your help! Love to see native software for Haiku!
