### ISSUE TITLE
Move "Feed entry" file type to "application"

### ISSUE THREAD

**Issue by humdingerb** [JadedCtrl/Pogger#9]
I'm not 100% sure on that one, but since the "Feed entry" files are just empty files with all data in their attributes, I think `text/x-feed-entry` should actually be `application/x-feed-entry`.

Also, sentence cased, the type name would be "Feed entry", the description "Atom/RSS feed entry".

**Comment by JadedCtrl** [comment]
They can't reliably be treated as text files, yea. This makes more sense, thanks. Changed with 2147c43.

**Comment by humdingerb** [comment]
BTW, in case you are unaware, if you put e.g. "Fixes #9" at the end of your commit message, github will automatically close issue #9 for you.

**Comment by JadedCtrl** [comment]
I had no idea haha, that's useful!
